linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - gosec
    - bodyclose
    - gocyclo
    - misspell
  disable:
    - unused
    - unparam
    - staticcheck
    - unconvert
